# Generated by Django 5.1.9 on 2025-06-01 14:37

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0039_alter_teaminvite_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pretalx_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretalx_activitylog_webhooks', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('object', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=1000)),
                ('status', models.CharField(default='PENDING', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('topic', models.CharField(max_length=250, null=True)),
                ('webhook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', related_query_name='event', to='pretalx_activitylog_webhook.webhook')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', related_query_name='secret', to='pretalx_activitylog_webhook.webhook')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=200)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_action_types', to='pretalx_activitylog_webhook.webhook')),
            ],
            options={
                'unique_together': {('webhook', 'action_type')},
            },
        ),
    ]
